### Esercizio NumPY 08/10

## Subarrays as no-copy views

In [26]:
import numpy as np #importo package

**ESERCIZIO 3**
***

**Creare un array es3 di valori casuali interi (randint) di dimensione 3x3, con valore massimo (incluso) uguale a 20.**

In [27]:
es3 = np.random.randint(21, size=(3,3))

1. **visualizzare es3**

In [28]:
print(es3)

[[ 2  1  7]
 [18 10 10]
 [18  5 13]]


2. **estrarre il subarray formato dalla seconda riga (es3-sub) come vista e visualizzarlo**

In [29]:
es3_sub = es3[1, :]
print(es3_sub)

[18 10 10]


3. **moltiplicare per 3 tutti gli elementi della seconda colonna di es3**

In [30]:
es3[:, 1]= es3[:, 1]*3
print(es3[:,1])

[ 3 30 15]


4. **visualizzare es3-sub. È cambiato rispetto a prima?** Si è cambiato.

In [31]:
print(es3_sub)

[18 30 10]


5. **estrarre il subarray formato dalla terza colonna di es3 come copia (es3-sub-copy)**

In [32]:
es3_sub_copy = es3[:,2].copy()
print(es3_sub_copy)

[ 7 10 13]


6. **sommare 10 a tutti gli elementi di es3-sub-copy e visualizzare**

In [33]:
es3_sub_copy = es3_sub_copy+10
print(es3_sub_copy)

[17 20 23]


7. **visualizzare es3. Contiene la modifica del punto 6?** No, non la contiene.

In [34]:
print(es3)

[[ 2  3  7]
 [18 30 10]
 [18 15 13]]
