### Esercizio NumPy 07-08/10

## Array Slicing: Accessing Subarrays

### One-dimensional subarrays
***

1. **Cambiare l’array creandone uno sempre di 10 valori ma che parta da 5 fino a 15 (incluso o [escluso]?)**

In [90]:
import numpy as np
x = np.arange(5, 15)
print(x)

[ 5  6  7  8  9 10 11 12 13 14]


2. **primi sei valori**

In [91]:
x[:6]

array([ 5,  6,  7,  8,  9, 10])

3. **elementi dopo l’indice 3**

In [92]:
x[3:] 

array([ 8,  9, 10, 11, 12, 13, 14])

4. **elementi dopo il terzo elemento**

In [93]:
x[2:]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

5. **subarray con valori 8,9,10,11,12**

In [94]:
x[3:8]

array([ 8,  9, 10, 11, 12])

6. **un elemento ogni tre, partendo dal primo**

In [95]:
x[1::3] 

array([ 6,  9, 12])

7. **un elemento ogni tre partendo dal terzo elemento**

In [96]:
x[2::3]

array([ 7, 10, 13])

### Multi-dimensional subarrays
***

1. **ESERCIZIO 2A: Creare un array es2a di valori casuali interi (randint) di dimensione 4x6, convalore massimo (incluso) uguale a 15.**

In [97]:
es2a = np.random.randint(16, size=(4, 6))
print(es2a)

[[15  5  0  6 10  7]
 [ 2 14 10 12  7  9]
 [ 4 15 12 15 10 12]
 [10  4  8 10  7 15]]


+ **prime tre righe, prime tre colonne**

In [98]:
es2a[:3,:3]

array([[15,  5,  0],
       [ 2, 14, 10],
       [ 4, 15, 12]])

+ **seconda e terza riga, quarta, quinta e sesta colonna**

In [99]:
es2a[1:3, 3:6]

array([[12,  7,  9],
       [15, 10, 12]])

+ **elementi dopo il terzo elemento**

In [100]:
es2a[2:]

array([[ 4, 15, 12, 15, 10, 12],
       [10,  4,  8, 10,  7, 15]])

+ **invertire l’ordine delle sole righe; invertire l’ordine delle sole colonne**

In [101]:
es2a[::-1, :] #colonne

array([[10,  4,  8, 10,  7, 15],
       [ 4, 15, 12, 15, 10, 12],
       [ 2, 14, 10, 12,  7,  9],
       [15,  5,  0,  6, 10,  7]])

In [102]:
es2a[:, ::-1] #righe

array([[ 7, 10,  6,  0,  5, 15],
       [ 9,  7, 12, 10, 14,  2],
       [12, 10, 15, 12, 15,  4],
       [15,  7, 10,  8,  4, 10]])

2. **ESERCIZIO 2B: creare un array es2b di valori casuali interi (randint) di dimensione 5x5x2, con valore massimo (incluso) uguale a 30.**

In [103]:
es2b = np.random.randint(31, size=(2,5,5))
print(es2b)

[[[27 10 28 18 30]
  [30 15 28 30 18]
  [16 25 30 27  6]
  [13 28  1 13 22]
  [ 3  8 21 18 20]]

 [[ 1 26 17  6  4]
  [11  8  0 13 29]
  [15 27  1  2 24]
  [ 9 27 10 28 22]
  [29  2  7 29 14]]]


+ **selezionare il primo subarray, da quello le prime 2 righe e le colonne dalla seconda alla quarta**

In [104]:
es2b[0, 0:2, 1:4]

array([[10, 28, 18],
       [15, 28, 30]])

+ **selezionare da entrambi i subarray le prime due righe e prime due colonne e invertire righe e colonne**

In [105]:
a = es2b[::, 0:2, 0:2]
print(a)

[[[27 10]
  [30 15]]

 [[ 1 26]
  [11  8]]]


In [106]:
b = a[::, ::-1, ::] #invertite colonne
print(b)

[[[30 15]
  [27 10]]

 [[11  8]
  [ 1 26]]]


In [107]:
c = a[::, ::, ::-1] #invertite righe
print(c)

[[[10 27]
  [15 30]]

 [[26  1]
  [ 8 11]]]
