### Esercizio NumPy 01/10

## NumPy Array Attributes

+ **Cosa fa la funzione np.random.randint?** Crea una lista casuale entro un determinato intervallo di numeri interi
+ **Cosa rappresentano ndim, shape, size?** ndim si riferisce al numero delle dimensioni; shape si riferisce al numero di tuple/colonne per ogni dimensione; size si riferisce al numero di elementi nella lista.
+ **Cosa significa dtype: int64?** Numero intero che va da -9223372036854775808 a 9223372036854775807

1. **Visualizzare i parametri ndim, shape e size anche degli array x1 e x2**

In [51]:
import numpy as np #visualizza ndim, shape e size anche per x1 e x2
np.random.seed(0)  
x1 = np.random.randint(8, size=3)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [52]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x1 ndim:  1
x1 shape: (3,)
x1 size:  3
x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


2. **Modificare x1 in modo che ndim sia uguale a 2 e shape sia uguale a (4, 5)**

In [53]:
import numpy as np
np.random.seed(0)  
x1 = np.random.randint(8, size=(4, 5))

In [54]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  2
x1 shape: (4, 5)
x1 size:  20


3. **Visualizzare i valori di x1**

In [55]:
print(x1) #visualizza i valori di x1

[[4 7 5 0 3]
 [3 3 7 1 3]
 [5 2 4 7 6]
 [0 0 4 2 1]]


4. **Cosa indica il primo parametro di random.randint posto al valore 10?** Indica il valore più alto (maggiore) che gli elementi della lista possono assumere

5. **Cambiarlo e visualizzare i nuovi valori dell’array**

In [56]:
x4 = np.random.randint(12, size=3)
print(x4)

[6 7 7]


## Array Indexing: Accessing Single Elements

1. **Creare un array es1 di valori casuali interi (randint) di dimensione 3x5, con valore massimo (incluso) uguale a 8. Visualizzare es1**

In [57]:
import numpy as np
np.random.seed(0)

es1 = np.random.randint(9, size=(3,5)) #crea e visualizza es1
print(es1)

[[5 0 3 3 7]
 [3 5 2 4 7]
 [6 8 8 1 6]]


2. **Selezionare gli elementi che hanno valore 5 (5 è un esempio, ovviamente potete scegliere un valore diverso), prima utilizzando la posizione come indice, poi usando la forma negativa dalla fine dell’array (vedere esempi)**

In [58]:
es1[0,0], es1[1,1] #utilizzo la posizione come indice

(5, 5)

In [59]:
es1[-2,-4], es1[1,-4] #utilizzo la forma negativa

(5, 5)

3. **Selezionare il primo elemento della seconda riga, il quinto elemento della prima riga, il secondo elemento della seconda colonna, il quarto elemento della terza colonna**

In [60]:
es1[0,2] #primo elemento seconda riga

3

In [61]:
es1[0,4] #quinto elemento prima riga

7

In [62]:
es1[1,1] #secondo elemento seconda colonna

5

In [63]:
es1[2,2] #terzo elemento terza colonna

8

4. **Sommare 10 all’elemento es1[0,0], sottrarre 5 all’elemento es1[3,2],
sommare l’elemento es1[0,0] all’elemento es1[1,0] e il risultato metterlo in
es1[2,0] (non usare i valori, usare i riferimenti alle posizioni dell’array)**

In [64]:
x3 = es1[0,0] + 10, es1[2,2] - 5, es1[0,0] + es1[1,0]
print(x3)

(15, 3, 8)
