### Esercizio NumPy 08/10

## Reshaping of Arrays and Array Concatenation and Splitting

In [35]:
import numpy as np

**ESERCIZIO 4**
***

1. **Creare una lista es4 di 36 valori interi crescenti partendo da 1**

In [36]:
es4 = np.arange(1,37)
print(es4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


2. **Trasformarlo in un array di dimensione 6x6**

In [37]:
es4 = es4.reshape(6,6)
print(es4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


3. **Estrarre tre subarray di dimensione 2x2 dalle prime due colonne (sub1, sub2, sub3)**

In [38]:
sub1 = es4[:2,0:2]
sub2 = es4[2:4,0:2]
sub3 = es4[4:6, 0:2]
print(sub1)
print(sub2)
print(sub3)

[[1 2]
 [7 8]]
[[13 14]
 [19 20]]
[[25 26]
 [31 32]]


4. **Concatenarli (usare concatenate) prima usando axis=0 poi con axis=1**

In [39]:
np.concatenate([sub1, sub2, sub3], axis=0) #verticale

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [40]:
np.concatenate([sub1, sub2, sub3], axis=1) #orizzontale

array([[ 1,  2, 13, 14, 25, 26],
       [ 7,  8, 19, 20, 31, 32]])

5. **Da es4 estrarre un subarray formato dalle prime due righe (sub4)**

In [41]:
sub4 = es4[0:2,:]
print(sub4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


6. **Concatenare sub1 a sub4. Usate hstack o vstack?** hstack

In [42]:
np.hstack([sub1, sub4])

array([[ 1,  2,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  7,  8,  9, 10, 11, 12]])

7. **Trasformate sub4 da 2x6 a 6x2 (le 2 righe diventano 2 colonne)**

In [43]:
sub4 = sub4.reshape(6,2)
print(sub4)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


8. **Concatenate sub1, sub2 e sub3 a formare un nuovo array 6x2 (sub5)**

In [44]:
sub5 = np.concatenate([sub1, sub2, sub3])
print(sub5)

[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]


9. **Concatenate sub4 (trasformato) con sub5. hstack o vstack?** Entrambi vanno bene

In [45]:
np.hstack([sub4, sub5])

array([[ 1,  2,  1,  2],
       [ 3,  4,  7,  8],
       [ 5,  6, 13, 14],
       [ 7,  8, 19, 20],
       [ 9, 10, 25, 26],
       [11, 12, 31, 32]])

In [46]:
np.vstack([sub4, sub5])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])