### Esercizio NumPy 01/10

## Creating Arrays from Scratch

In [12]:
import numpy as np #importo package

1. **np.zeros() creare lista di 50 elementi**

In [13]:
np.zeros(50, dtype=int) #crea una lista di numeri interi, in questo caso di ZERO

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

2. **np.ones() : creare matrice 2x5, di numeri interi**

In [14]:
np.ones((2, 5), dtype=int) #crea una lista di numeri interi, in questo caso UNO

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

3. **np.full() : creare matrice 3x3 con valori 12.34**

In [15]:
np.full((3, 3), 12.34) #crea una lista riempita di un determinato numero

array([[12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34]])

4. **np.arange() : creare lista di 10 elementi, che inizia da 6 e incrementa di 4**

In [16]:
np.arange(6, 10, 4) #crea una lista in un determinato intervallo con un determinato salto di numeri

array([6])

5. **np.linespace(): creare lista di elementi tra 0 e 100 distanziati di 5**

In [23]:
np.linspace(0, 100, 5) #crea una lista in un determinato intervallo, specificando i gruppi di divisione

array([  0.,  25.,  50.,  75., 100.])

6. **np.random.random() : creare matrice 1x10 di valori casuali tra 0 e 1**

In [18]:
np.random.random((1, 10)) #crea una lista compresa tra 0 e 1

array([[0.86280772, 0.50495635, 0.19002308, 0.61899367, 0.39236908,
        0.80759759, 0.39312175, 0.00745745, 0.40310756, 0.08941064]])

7. **np.random.normal() : creare matrice 2x10 di valori con distribuzione gaussiana con media 0 e deviazione standard 1**

In [19]:
np.random.normal(0, 1, (2, 10)) #crea una lista con una determinata media e varianza (0 e 1, distribuzione gaussiana)

array([[ 0.0402801 ,  0.38889922,  0.83427441,  1.33248986, -1.06712906,
         1.1233466 , -0.30743041,  0.32057192, -0.25766667,  1.3256235 ],
       [-0.19695412,  0.35577702, -0.01178922, -0.47525563,  0.22311099,
         0.20317274,  0.64025104, -0.9636842 , -0.90498484, -0.21861098]])